server:
  port: 8888
  servlet:
    context-path: /

limit:
  minMoney: 2
  maxMoney: 100
  desc: 最低${limit.minMoney}最高${limit.maxMoney}

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/business?serverTimezone=GMT%2B8
      username: root
      password: root
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
mybatis:
  mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
logging:
    level:
      com.neuedu.dao: debug







